/**
 * Seed ClauseDefinition rows for all 88 GIGW 3.0 clauses.
 *
 * Source: requirements.md §4 (5.1), §5 (5.2), §6 (5.3), §8 (5.4)
 * Run:    npm run db:seed  (from packages/db, after migration)
 *
 * Automation values match requirements.md §0 terminology note:
 *   "automatable"  → ClauseAutomation.automatable
 *   "semi"         → ClauseAutomation.semi_automatable
 *   "manual-only"  → ClauseAutomation.manual_only
 */

import { PrismaClient } from "@prisma/client";
import type {
  ClauseCategory,
  ClauseAutomation,
  Severity,
} from "@prisma/client";

const prisma = new PrismaClient();

interface ClauseSeed {
  clauseId: string;
  section: ClauseCategory;
  title: string;
  description: string;
  automation: ClauseAutomation;
  severity: Severity;
  ownerMember: string;
  checkerId: string | null;
}

const clauses: ClauseSeed[] = [
  // ── §5.1 Quality (25 clauses) — Owner: B ────────────────────────────────
  {
    clauseId: "5.1.1",
    section: "quality",
    title: "State Emblem/logo on homepage",
    description: "State Emblem/logo present on homepage with proper ratio/colour and alt text",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-logo",
  },
  {
    clauseId: "5.1.2",
    section: "quality",
    title: "Ownership info on homepage and entry pages",
    description: "Ownership information present on homepage and all entry pages",
    automation: "automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-ownership",
  },
  {
    clauseId: "5.1.3",
    section: "quality",
    title: "Source cited for reproduced documents",
    description: "Source is cited for all reproduced documents",
    automation: "manual_only",
    severity: "low",
    ownerMember: "B",
    checkerId: null,
  },
  {
    clauseId: "5.1.4",
    section: "quality",
    title: "Due permission for copyrighted content",
    description: "Due permission has been obtained for all copyrighted content",
    automation: "manual_only",
    severity: "high",
    ownerMember: "B",
    checkerId: null,
  },
  {
    clauseId: "5.1.5",
    section: "quality",
    title: "Last updated/reviewed date shown",
    description: "Last updated or reviewed date is shown on pages",
    automation: "automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "quality-last-updated",
  },
  {
    clauseId: "5.1.6",
    section: "quality",
    title: "Downloadable material metadata",
    description: "Downloadable material shows title, size, format, and instructions",
    automation: "semi_automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "quality-download-meta",
  },
  {
    clauseId: "5.1.7",
    section: "quality",
    title: "Circulars/notifications/forms/schemes metadata",
    description: "Circulars, notifications, forms and schemes list title, language, purpose and validity",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-circular-meta",
  },
  {
    clauseId: "5.1.8",
    section: "quality",
    title: "Outdated content removed or archived",
    description: "Outdated content is removed from live site or archived",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-stale-content",
  },
  {
    clauseId: "5.1.9",
    section: "quality",
    title: "About Us section present and current",
    description: "An About Us section is present and kept up to date",
    automation: "semi_automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "quality-about-us",
  },
  {
    clauseId: "5.1.10",
    section: "quality",
    title: "Contact Us page with complete details",
    description: "Contact Us page with complete details is linked from the homepage",
    automation: "automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-contact-us",
  },
  {
    clauseId: "5.1.11",
    section: "quality",
    title: "Feedback via online forms",
    description: "Feedback is collected via online forms with a timely response process",
    automation: "semi_automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "quality-feedback-form",
  },
  {
    clauseId: "5.1.12",
    section: "quality",
    title: "Link to National Portal (india.gov.in)",
    description: "Prominent link to india.gov.in present, opens in new window",
    automation: "automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "quality-national-portal-link",
  },
  {
    clauseId: "5.1.13",
    section: "quality",
    title: "Multi-browser tested; Hindi/regional fonts render correctly",
    description: "Site tested across browsers; Hindi/regional fonts render without layout loss",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "B",
    checkerId: null,
  },
  {
    clauseId: "5.1.14",
    section: "quality",
    title: "Help section linked from all pages",
    description: "Help section is linked from all pages in a consistent location",
    automation: "semi_automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "quality-help-link",
  },
  {
    clauseId: "5.1.15",
    section: "quality",
    title: "CSS-based layout and responsive design",
    description: "Site uses CSS-based layout with responsive design",
    automation: "automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-responsive",
  },
  {
    clauseId: "5.1.16",
    section: "quality",
    title: "Content readable with style sheets off",
    description: "Content remains readable when style sheets are disabled",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-no-css",
  },
  {
    clauseId: "5.1.17",
    section: "quality",
    title: "Page title, lang attribute, metadata",
    description: "Each page has a descriptive title, correct lang attribute, and keywords/description metadata",
    automation: "automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-page-metadata",
  },
  {
    clauseId: "5.1.18",
    section: "quality",
    title: "Minimum prescribed content on pages",
    description: "Homepage and subsequent pages contain all minimum GIGW-prescribed content elements",
    automation: "automatable",
    severity: "high",
    ownerMember: "B",
    checkerId: "quality-min-content",
  },
  {
    clauseId: "5.1.19",
    section: "quality",
    title: "Data table markup",
    description: "Data tables use proper row/column headers, associated cells, and captions",
    automation: "automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-table-markup",
  },
  {
    clauseId: "5.1.20",
    section: "quality",
    title: "Content prints correctly on A4",
    description: "Content prints correctly on A4 paper",
    automation: "semi_automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "quality-print",
  },
  {
    clauseId: "5.1.21",
    section: "quality",
    title: "Official domain (.gov.in/.nic.in)",
    description: "Site uses an official .gov.in or .nic.in domain (or eligible .edu.in/.res.in/.ac.in)",
    automation: "automatable",
    severity: "high",
    ownerMember: "B",
    checkerId: "quality-domain",
  },
  {
    clauseId: "5.1.22",
    section: "quality",
    title: "API integration with India Portal ecosystem",
    description: "Site integrates with India Portal, DigiLocker, Aadhaar, SSO, MyGov, MyScheme, and/or Data Platform",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "quality-india-portal-integration",
  },
  {
    clauseId: "5.1.23",
    section: "quality",
    title: "Consistent UX/visual identity across organisation",
    description: "Consistent UX and visual identity maintained across the organisation's websites and apps",
    automation: "manual_only",
    severity: "low",
    ownerMember: "B",
    checkerId: null,
  },
  {
    clauseId: "5.1.24",
    section: "quality",
    title: "Two-way social media integration",
    description: "Two-way social media integration is present",
    automation: "automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "quality-social-media",
  },
  {
    clauseId: "5.1.25",
    section: "quality",
    title: "Content free from spelling/grammatical errors",
    description: "Content is free from spelling and grammatical errors",
    automation: "semi_automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "quality-spelling",
  },

  // ── §5.2 Accessibility (50 clauses) — Owner: A ───────────────────────────
  {
    clauseId: "5.2.1",
    section: "accessibility",
    title: "Text alternatives for non-text content",
    description: "All non-text content has a text alternative (WCAG 1.1.1)",
    automation: "semi_automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-text-alternatives",
  },
  {
    clauseId: "5.2.2",
    section: "accessibility",
    title: "Alternative for prerecorded audio/video-only",
    description: "Prerecorded audio-only and video-only content has an alternative (WCAG 1.2.1)",
    automation: "manual_only",
    severity: "high",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.3",
    section: "accessibility",
    title: "Captions for prerecorded audio in sync media",
    description: "Prerecorded audio in synchronised media has captions (WCAG 1.2.2)",
    automation: "semi_automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-captions",
  },
  {
    clauseId: "5.2.4",
    section: "accessibility",
    title: "Audio description or text alternative for video",
    description: "Prerecorded video in synchronised media has an audio description or text alternative (WCAG 1.2.3)",
    automation: "manual_only",
    severity: "high",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.5",
    section: "accessibility",
    title: "Captions for live audio",
    description: "Live audio in synchronised media has captions (WCAG 1.2.4)",
    automation: "manual_only",
    severity: "high",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.6",
    section: "accessibility",
    title: "Audio description for prerecorded video",
    description: "Prerecorded video has an audio description (WCAG 1.2.5)",
    automation: "manual_only",
    severity: "high",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.7",
    section: "accessibility",
    title: "Info and relationships programmatically determinable",
    description: "Information, structure, and relationships are programmatically determinable (WCAG 1.3.1)",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.8",
    section: "accessibility",
    title: "Meaningful sequence",
    description: "Reading and navigation sequence is meaningful (WCAG 1.3.2)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-keyboard",
  },
  {
    clauseId: "5.2.9",
    section: "accessibility",
    title: "Sensory characteristics not sole instruction method",
    description: "Instructions do not rely solely on sensory characteristics (WCAG 1.3.3)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.10",
    section: "accessibility",
    title: "Orientation not restricted",
    description: "Content is not restricted to a single display orientation (WCAG 1.3.4)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-reflow",
  },
  {
    clauseId: "5.2.11",
    section: "accessibility",
    title: "Identify input purpose (autofill)",
    description: "The purpose of input fields can be programmatically determined (WCAG 1.3.5)",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.12",
    section: "accessibility",
    title: "Use of colour not sole indicator",
    description: "Colour is not the only visual means of conveying information (WCAG 1.4.1)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-colour",
  },
  {
    clauseId: "5.2.13",
    section: "accessibility",
    title: "Audio control (autoplay > 3s)",
    description: "Audio that plays automatically for more than 3 seconds can be paused or stopped (WCAG 1.4.2)",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.14",
    section: "accessibility",
    title: "Contrast minimum 4.5:1",
    description: "Text has a contrast ratio of at least 4.5:1 against its background (WCAG 1.4.3)",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.15",
    section: "accessibility",
    title: "Resize text to 200%",
    description: "Text can be resized up to 200% without loss of content or functionality (WCAG 1.4.4)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-reflow",
  },
  {
    clauseId: "5.2.16",
    section: "accessibility",
    title: "Images of text avoided",
    description: "Images of text are not used except where essential (WCAG 1.4.5)",
    automation: "semi_automatable",
    severity: "low",
    ownerMember: "A",
    checkerId: "a11y-images-of-text",
  },
  {
    clauseId: "5.2.17",
    section: "accessibility",
    title: "Reflow at 320px/256px",
    description: "Content reflows at a width of 320 CSS pixels without horizontal scrolling (WCAG 1.4.10)",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-reflow",
  },
  {
    clauseId: "5.2.18",
    section: "accessibility",
    title: "Non-text contrast 3:1",
    description: "UI components and graphical objects have a contrast ratio of at least 3:1 (WCAG 1.4.11)",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.19",
    section: "accessibility",
    title: "Text spacing overrides don't break content",
    description: "No loss of content when text spacing is overridden (WCAG 1.4.12)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-text-spacing",
  },
  {
    clauseId: "5.2.20",
    section: "accessibility",
    title: "Content on hover/focus dismissible, hoverable, persistent",
    description: "Additional content triggered by hover or focus is dismissible, hoverable, and persistent (WCAG 1.4.13)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.21",
    section: "accessibility",
    title: "Keyboard operable",
    description: "All functionality is operable through a keyboard interface (WCAG 2.1.1)",
    automation: "semi_automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-keyboard",
  },
  {
    clauseId: "5.2.22",
    section: "accessibility",
    title: "No keyboard trap",
    description: "Keyboard focus is not trapped in any component (WCAG 2.1.2)",
    automation: "semi_automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-keyboard",
  },
  {
    clauseId: "5.2.23",
    section: "accessibility",
    title: "Character key shortcuts remappable or off",
    description: "Single-character key shortcuts can be turned off or remapped (WCAG 2.1.4)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.24",
    section: "accessibility",
    title: "Timing adjustable",
    description: "Time limits are adjustable or can be turned off (WCAG 2.2.1)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.25",
    section: "accessibility",
    title: "Pause/stop/hide moving content",
    description: "Moving, blinking, or auto-updating content can be paused, stopped, or hidden (WCAG 2.2.2)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-motion",
  },
  {
    clauseId: "5.2.26",
    section: "accessibility",
    title: "No content flashes more than 3 times per second",
    description: "No content flashes more than three times per second (WCAG 2.3.1)",
    automation: "semi_automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-flashing",
  },
  {
    clauseId: "5.2.27",
    section: "accessibility",
    title: "Bypass blocks (skip links)",
    description: "A mechanism to bypass repeated blocks of content is available (WCAG 2.4.1)",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.28",
    section: "accessibility",
    title: "Page titled",
    description: "Web pages have titles that describe their topic or purpose (WCAG 2.4.2)",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.29",
    section: "accessibility",
    title: "Focus order preserves meaning",
    description: "Components receive focus in an order that preserves meaning (WCAG 2.4.3)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-focus-order",
  },
  {
    clauseId: "5.2.30",
    section: "accessibility",
    title: "Link purpose from text or context",
    description: "The purpose of each link can be determined from the link text or context (WCAG 2.4.4)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-link-purpose",
  },
  {
    clauseId: "5.2.31",
    section: "accessibility",
    title: "Multiple ways to locate a page",
    description: "More than one way is available to locate a page (WCAG 2.4.5)",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.32",
    section: "accessibility",
    title: "Headings and labels describe topic",
    description: "Headings and labels describe topic or purpose (WCAG 2.4.6)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-headings",
  },
  {
    clauseId: "5.2.33",
    section: "accessibility",
    title: "Focus visible",
    description: "Any keyboard operable UI component has a visible focus indicator (WCAG 2.4.7)",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.34",
    section: "accessibility",
    title: "Pointer gestures have single-pointer alternative",
    description: "Multi-point or path-based gestures have a single-pointer alternative (WCAG 2.5.1)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.35",
    section: "accessibility",
    title: "Pointer cancellation",
    description: "Single-pointer actions can be cancelled (WCAG 2.5.2)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.36",
    section: "accessibility",
    title: "Label in name matches visible text",
    description: "Accessible name includes the visible label text (WCAG 2.5.3)",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.37",
    section: "accessibility",
    title: "Motion actuation has UI alternative",
    description: "Functionality triggered by device motion has a UI alternative (WCAG 2.5.4)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.38",
    section: "accessibility",
    title: "Page language set",
    description: "The default human language of each page is programmatically determinable (WCAG 3.1.1)",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.39",
    section: "accessibility",
    title: "Language of parts marked",
    description: "The language of passages in a different language is programmatically determinable (WCAG 3.1.2)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-language-parts",
  },
  {
    clauseId: "5.2.40",
    section: "accessibility",
    title: "No context change on focus",
    description: "Components do not initiate a change of context on focus (WCAG 3.2.1)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.41",
    section: "accessibility",
    title: "No unexpected context change on input",
    description: "Changing the setting of a UI component does not automatically cause a context change (WCAG 3.2.2)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.42",
    section: "accessibility",
    title: "Consistent navigation order",
    description: "Navigation mechanisms are presented in the same relative order across pages (WCAG 3.2.3)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-navigation",
  },
  {
    clauseId: "5.2.43",
    section: "accessibility",
    title: "Consistent identification of components",
    description: "Components with the same function are identified consistently (WCAG 3.2.4)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-navigation",
  },
  {
    clauseId: "5.2.44",
    section: "accessibility",
    title: "Input errors identified in text",
    description: "Input errors are identified and described in text (WCAG 3.3.1)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-error-id",
  },
  {
    clauseId: "5.2.45",
    section: "accessibility",
    title: "Labels or instructions for user input",
    description: "Labels or instructions are provided when content requires user input (WCAG 3.3.2)",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.46",
    section: "accessibility",
    title: "Error correction suggestions",
    description: "Error correction suggestions are provided if an input error is detected (WCAG 3.3.3)",
    automation: "manual_only",
    severity: "medium",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.47",
    section: "accessibility",
    title: "Error prevention for legal/financial/data actions",
    description: "Submissions are reversible, checked, or confirmed for legal, financial, or data-modifying actions (WCAG 3.3.4)",
    automation: "manual_only",
    severity: "high",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.2.48",
    section: "accessibility",
    title: "Valid markup",
    description: "No duplicate IDs, proper element nesting, complete start/end tags (WCAG 4.1.1)",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.49",
    section: "accessibility",
    title: "Name, role, value programmatically determinable",
    description: "Name, role, and value of UI components are programmatically determinable (WCAG 4.1.2)",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "a11y-axe-core",
  },
  {
    clauseId: "5.2.50",
    section: "accessibility",
    title: "Status messages without focus",
    description: "Status messages can be programmatically determined without receiving focus (WCAG 4.1.3)",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "a11y-status-messages",
  },

  // ── §5.3 Cybersecurity (automatable + semi only) — Owner: A ─────────────
  // manual-only clauses are included for the manual-review checklist
  {
    clauseId: "5.3.1",
    section: "cybersecurity",
    title: "Security Audit Clearance certificate",
    description: "Security Audit Clearance certificate from NIC/STQC/CERT-In empanelled auditor obtained",
    automation: "manual_only",
    severity: "high",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.3.1-code-headers",
    section: "cybersecurity",
    title: "HTTP response headers obscured",
    description: "HTTP response headers do not disclose server type, version, or technology stack",
    automation: "automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "sec-headers",
  },
  {
    clauseId: "5.3.1-code-cookies",
    section: "cybersecurity",
    title: "Cookies are Secure and HttpOnly",
    description: "All cookies have the Secure and HttpOnly flags set",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "sec-cookies",
  },
  {
    clauseId: "5.3.1-code-errors",
    section: "cybersecurity",
    title: "Custom error pages (no stack trace exposure)",
    description: "Custom error pages are shown without exposing stack traces or server paths",
    automation: "semi_automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "sec-error-page",
  },
  {
    clauseId: "5.3.1-code-tls-comms",
    section: "cybersecurity",
    title: "3rd-party/API comms encrypted",
    description: "All third-party and API communications visible in page network traffic are encrypted",
    automation: "semi_automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "sec-tls-comms",
  },
  {
    clauseId: "5.3.1-code-mfa",
    section: "cybersecurity",
    title: "MFA / password policy on login",
    description: "MFA and password policy enforced on login — manual verification required",
    automation: "manual_only",
    severity: "high",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.3.2",
    section: "cybersecurity",
    title: "Hosting environment secured",
    description: "Hosting environment meets CIA (Confidentiality, Integrity, Availability) requirements — manual verification required",
    automation: "manual_only",
    severity: "high",
    ownerMember: "A",
    checkerId: null,
  },
  {
    clauseId: "5.3.2-tls",
    section: "cybersecurity",
    title: "Valid SSL/TLS certificate (≥2048-bit SHA-256)",
    description: "Site has a valid SSL/TLS certificate with at least 2048-bit key and SHA-256 or stronger",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "sec-tls",
  },
  {
    clauseId: "5.3.2-https",
    section: "cybersecurity",
    title: "HTTPS enforced, HTTP disabled, HSTS present",
    description: "HTTPS is enforced, HTTP redirects to HTTPS, and HSTS header is present",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "sec-tls",
  },
  {
    clauseId: "5.3.2-ciphers",
    section: "cybersecurity",
    title: "Weak protocols/ciphers disabled",
    description: "SSLv2/v3, TLS 1.0/1.1, 3DES, RC4 and other weak ciphers are disabled",
    automation: "automatable",
    severity: "high",
    ownerMember: "A",
    checkerId: "sec-tls",
  },
  {
    clauseId: "5.3.2-waf",
    section: "cybersecurity",
    title: "Web Application Firewall present",
    description: "A Web Application Firewall is present and active",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "sec-waf",
  },
  {
    clauseId: "5.3.3",
    section: "cybersecurity",
    title: "Security Policy, Privacy Policy, Contingency Plan published",
    description: "Security Policy, Privacy Policy, and Contingency Plan are defined and published on the site",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "A",
    checkerId: "sec-policies",
  },

  // ── §5.4 Lifecycle (10 clauses) — Owner: B ───────────────────────────────
  {
    clauseId: "5.4.1",
    section: "lifecycle",
    title: "Web Information Manager (WIM) nominated",
    description: "A Web Information Manager is nominated and their contact details are displayed on the site",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "lifecycle-wim",
  },
  {
    clauseId: "5.4.2",
    section: "lifecycle",
    title: "Website URL on organisational stationery",
    description: "Website URL appears on all organisational stationery and publicity material",
    automation: "manual_only",
    severity: "low",
    ownerMember: "B",
    checkerId: null,
  },
  {
    clauseId: "5.4.3",
    section: "lifecycle",
    title: "Copyright and policy documents defined",
    description: "Copyright, CMAP, CAP, CRP, Hyperlinking, T&C, and Monitoring Plan policies are defined and accessible",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "lifecycle-policies",
  },
  {
    clauseId: "5.4.4",
    section: "lifecycle",
    title: "Hyperlink accuracy and external link indicators",
    description: "Hyperlink accuracy is maintained and external links are clearly indicated",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "lifecycle-hyperlinks",
  },
  {
    clauseId: "5.4.5",
    section: "lifecycle",
    title: "Content free of offensive/discriminatory language",
    description: "Content is free of offensive or discriminatory language",
    automation: "semi_automatable",
    severity: "high",
    ownerMember: "B",
    checkerId: "lifecycle-content-moderation",
  },
  {
    clauseId: "5.4.6",
    section: "lifecycle",
    title: "Multi-language versions updated simultaneously",
    description: "All language versions of the site are updated simultaneously",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "lifecycle-multilang-sync",
  },
  {
    clauseId: "5.4.7",
    section: "lifecycle",
    title: "No broken links",
    description: "No broken internal or external links on the site",
    automation: "automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "lifecycle-broken-links",
  },
  {
    clauseId: "5.4.8",
    section: "lifecycle",
    title: "No under construction pages",
    description: "No pages are in an under construction state",
    automation: "automatable",
    severity: "low",
    ownerMember: "B",
    checkerId: "lifecycle-under-construction",
  },
  {
    clauseId: "5.4.9",
    section: "lifecycle",
    title: "Documents in HTML or accessible formats",
    description: "Documents are provided in HTML or other accessible formats, not scanned-image-only PDFs",
    automation: "semi_automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "lifecycle-accessible-docs",
  },
  {
    clauseId: "5.4.10",
    section: "lifecycle",
    title: "Bilingual with prominent language selector",
    description: "Site is bilingual with a prominent language selector and uses Unicode characters",
    automation: "automatable",
    severity: "medium",
    ownerMember: "B",
    checkerId: "lifecycle-bilingual",
  },
];

async function main(): Promise<void> {
  console.log(`Seeding ${clauses.length} ClauseDefinition rows...`);

  let created = 0;
  let skipped = 0;

  for (const clause of clauses) {
    await prisma.clauseDefinition.upsert({
      where: { clauseId: clause.clauseId },
      update: {
        // Update metadata on re-seed (title, description, severity may be tuned)
        title: clause.title,
        description: clause.description,
        automation: clause.automation,
        severity: clause.severity,
        checkerId: clause.checkerId,
      },
      create: clause,
    });

    if (await wasCreated(clause.clauseId)) {
      created++;
    } else {
      skipped++;
    }
  }

  console.log(`Done. ${clauses.length} rows upserted (${created} new, ${skipped} updated).`);

  // Sanity checks
  const total = await prisma.clauseDefinition.count();
  const byA = await prisma.clauseDefinition.count({ where: { ownerMember: "A" } });
  const byB = await prisma.clauseDefinition.count({ where: { ownerMember: "B" } });

  console.log(`\nVerification:`);
  console.log(`  Total clauses in DB : ${total}`);
  console.log(`  Owner A             : ${byA}`);
  console.log(`  Owner B             : ${byB}`);

  if (total !== clauses.length) {
    throw new Error(
      `Expected ${clauses.length} clauses but found ${total} in DB. Check for duplicate or missing clauseIds.`,
    );
  }
}

// Track creation vs update
async function wasCreated(clauseId: string): Promise<boolean> {
  const row = await prisma.clauseDefinition.findUnique({
    where: { clauseId },
    select: { clauseId: true },
  });
  return row !== null;
}

main()
  .catch((err: unknown) => {
    console.error("Seed failed:", err);
    process.exit(1);
  })
  .finally(() => {
    void prisma.$disconnect();
  });
